image: docker:latest
services:
  - docker:dind

stages:
  - build
  - deploy

docker-build:
  stage: build
  script:
    - docker login -u $CI_BUILD_USER -p $CI_BUILD_TOKEN registry.gitlab.com
    - docker build -t registry.gitlab.com/nietypowi/backend .
    - docker push registry.gitlab.com/nietypowi/backend
  when: manual

docker-deploy:
  stage: deploy
  image: registry.gitlab.com/nietypowi/backend
  script:
    - echo "performing deploy"
  only:
    - master
  when: manual

